## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -278.0
accel_x_max: 252.0
accel_y_min: -249.0
accel_y_max: 250.0
accel_z_min: -250.0
accel_z_max: 250.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: true
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

### gyroscope
gyro_average_offset_x: 0.0
gyro_average_offset_y: 0.0
gyro_average_offset_z: 0.0


#define ACCEL_X_MIN ((float) -278)
#define ACCEL_X_MAX ((float) 252)
#define ACCEL_Y_MIN ((float) -249)
#define ACCEL_Y_MAX ((float) 270)
#define ACCEL_Z_MIN ((float) -305)
#define ACCEL_Z_MAX ((float) 218)

// Magnetometer (standard calibration mode)
// "magn x,y,z (min/max) = X_MIN/X_MAX  Y_MIN/Y_MAX  Z_MIN/Z_MAX"
#define MAGN_X_MIN ((float) -600)
#define MAGN_X_MAX ((float) 600)
#define MAGN_Y_MIN ((float) -600)
#define MAGN_Y_MAX ((float) 600)
#define MAGN_Z_MIN ((float) -600)
#define MAGN_Z_MAX ((float) 600)

// Magnetometer (extended calibration mode)
// Uncommend to use extended magnetometer calibration (compensates hard & soft iron errors)
//const float magn_ellipsoid_center[3] = {-94.2016, -61.3600, -104.146};
//const float magn_ellipsoid_transform[3][3] = {{0.812137, -0.0247697, 0.0177242}, {-0.0247697, 0.813097, -0.0353210}, {0.0177242, -0.0353210, 0.990605}};
//#define CALIBRATION__MAGN_USE_EXTENDED true
//const float magn_ellipsoid_center[3] = {-94.6085, -78.2976, -84.3873};
//const float magn_ellipsoid_transform[3][3] = {{0.841361, -0.000241459, -0.00502140}, {-0.000241459, 0.835853, 0.00327189}, {-0.00502140, 0.00327189, 0.999776}};
